version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-ndis}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_DSN: ${DATABASE_DSN}
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}
      IBM_COS_ENABLED: ${IBM_COS_ENABLED}
      IBM_COS_ENDPOINT: ${IBM_COS_ENDPOINT}
      IBM_COS_API_KEY: ${IBM_COS_API_KEY}
      IBM_COS_INSTANCE_CRN: ${IBM_COS_INSTANCE_CRN}
      IBM_COS_BUCKET: ${IBM_COS_BUCKET}
      XERO_ENABLED: ${XERO_ENABLED}
      XERO_CLIENT_ID: ${XERO_CLIENT_ID}
      XERO_CLIENT_SECRET: ${XERO_CLIENT_SECRET}
      XERO_REDIRECT_URI: ${XERO_REDIRECT_URI}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  dbdata:
